import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const appApi = createApi({
  reducerPath: 'appApi',
  baseQuery: fetchBaseQuery({ baseUrl: '/api' }),
  tagTypes: [
    'Material',
    'StockBatch',
    'Job',
    'JobMaterials',
    'JobDailyQuantityLog',
    'Customer',
    'Supplier',
    'Transaction',
    'DispatchEntry',
    'DispatchEntryRevision',
    'ReceiptEntry',
    'StockValuation',
    'StockIntegrity',
    'Consumption',
    'JobProfitability',
    'SupplierTraceability',
    'StockExceptionApproval',
    'StockCountSession',
    'Unit',
    'Category',
    'Warehouse',
    'MaterialLog',
    'PriceLog',
    'Employee',
    'WorkSchedule',
    'AttendanceOverview',
    'AttendanceEntry',
    'HrDocumentType',
    'HrEmployeeTypeSettings',
    'HrExpertise',
  ],
  endpoints: () => ({}),
});
