ALTER TYPE "TransactionType" ADD VALUE IF NOT EXISTS 'ADJUSTMENT';

ALTER TYPE "StockExceptionType" ADD VALUE IF NOT EXISTS 'MANUAL_STOCK_ADJUSTMENT';

ALTER TABLE "StockExceptionApproval"
ADD COLUMN "payload" JSONB;
