/** Prisma `select` shapes for job/customer data used by print templates. */
export const customerForPrintSelect = {
  name: true,
  contactPerson: true,
  phone: true,
  email: true,
  address: true,
  trnNumber: true,
} as const;

export const jobForPrintSelect = {
  id: true,
  jobNumber: true,
  description: true,
  site: true,
  address: true,
  locationName: true,
  locationLat: true,
  locationLng: true,
  status: true,
  startDate: true,
  endDate: true,
  lpoNumber: true,
  lpoDate: true,
  lpoValue: true,
  quotationNumber: true,
  quotationDate: true,
  projectName: true,
  projectDetails: true,
  jobWorkValue: true,
  contactPerson: true,
  contacts: { orderBy: { sortOrder: 'asc' as const } },
  salesPerson: true,
  source: true,
  externalJobId: true,
  externalUpdatedAt: true,
  parentJobId: true,
  parentJob: { select: { jobNumber: true } },
  customerId: true,
  customer: { select: customerForPrintSelect },
} as const;
